### ISSUE TITLE
Crash (SIGSEGV) on startup in Linux

### ISSUE THREAD

**Issue by VenKamikaze** [thobbsinteractive/magic-carpet-2-hd#47]
Hi.

Found your project and tried to compile and run it.

I've got SDL2 2.0.20 + it's 32 bit libraries installed.

Unfortunately it crashes on VGA_Init for me with a segfault:

```
[me@eridani bin]$ ./remc2 
Segmentation fault (core dumped)
```

I ran it with gdb to get a backtrace. See below:

```
[me@eridani bin]$ gdb ./remc2 
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./remc2...
(gdb) r
Starting program: /home/msaun/build/magic-carpet-2-hd/build/inst/bin/remc2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0xf3581ac0 (LWP 1263)]
[New Thread 0xf2d0dac0 (LWP 1264)]
[New Thread 0xf250cac0 (LWP 1265)]
[New Thread 0xf1a2bac0 (LWP 1266)]

Thread 1 "remc2" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xf7e6fb22 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#2  0xf7e37278 in ?? () from /usr/lib32/libSDL2-2.0.so.0
#3  0xf7e3751a in ?? () from /usr/lib32/libSDL2-2.0.so.0
#4  0x56693797 in VGA_Init (width=1920, height=1080, maintainAspectRatio=true) at /home/msaun/build/magic-carpet-2-hd/remc2/portability/port_sdl_vga_mouse.cpp:402
#5  0x5669362e in VGA_Init (width=1920, height=1080, maintainAspectRatio=true) at /home/msaun/build/magic-carpet-2-hd/remc2/portability/port_sdl_vga_mouse.cpp:353
#6  0x5660f892 in sub_main (argc=1, argv=0xffffd744) at /home/msaun/build/magic-carpet-2-hd/remc2/sub_main.cpp:55920
#7  0x5655afdb in main (argc=1, argv=0xffffd744) at /home/msaun/build/magic-carpet-2-hd/remc2/remc2.cpp:24
```

**Comment by VenKamikaze** [comment]
Also, compilation was a little bit of a pain. 

I had to set in the main CMakeLists.txt:
set(CMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX "32")

Plus I had to comment out the CMakeLists lines in 'remc2' for the unit tests and the editor.

**Comment by VenKamikaze** [comment]
The crash mentioned above was in SDL_SetWindowGrab, however it was actually due to a missing lib32-pulse on my system.  Likely something else failed earlier causing SDL to be in a weird state. 

After fixing that, I hit numerous issues with case sensitivity in file & directory names, plus needing write permission (not sure why) on the corresponding files. I was able to correct that with a few scripts, and the game now launches.
